version: 0.2

env:
  variables:
    GOARCH="amd64"
    GOBIN=""
    GOEXE=""
    GOHOSTARCH="amd64"
    GOHOSTOS="linux"
    GOOS="linux"
    GOPATH="/go"
    GORACE=""
    GOROOT="/usr/local/go"
    GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
    GO15VENDOREXPERIMENT="1"
    CC="gcc"
    GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
    CXX="g++"
    CGO_ENABLED="1"
phases:      
  build:
    commands:
      - echo Build started on `date`
      - go build duoauth/duoauth.go
      - go install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - duoauth
